### ISSUE TITLE
impossible to connect on wifi

### ISSUE THREAD

**Issue by tguillaume02** [pcmihnea/HA_WMR500#11]
Hello,

I have a wmr500 but I can't configure the wifi with the Android application. So I tried to connect with telnet but impossible to connect with telenet.
I connect my laptop on the wmr500 wifi and I try to connect with telenet but without success.

Do you have tips ?

**Comment by pcmihnea** [comment]
Hi,

Perhaps the difference in behaviour may be due to a different firmware?
Once connected, could you check with a traffic sniffer (Wireshark) whether there's any activity from the WMR500? Does your pc get an IP address assigned?
You could also try resetting the wmr500, or use another pc/telnet terminal.

**Comment by pcmihnea** [comment]
Unfortunately, unless you have the security certificates from Oregon, there's no way to fully replicate their time server.
The easiest solution I could find is to modify the firmware and downgrade the time sync requests from HTTPS to HTTP, as documented in the readme.
